name: Node.js CI/CD

# Run when code is pushed or a pull request is opened on main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-test  # Only runs if tests pass
    if: github.ref == 'refs/heads/main'  # Only deploy on the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --production

      - name: Deploy to server
        run: |
          echo "Deploying to production..."
          # Example: scp -r ./dist user@yourserver:/var/www/app
          # or use a deploy action for AWS, Vercel, etc.
