name: passing_variables

on:
  work_flow:

jobs:
  producer:
    runs-on: ubuntu-24.04

    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
      - name: Generate and export foo
        id: generate-foo
        run: |
          foo=bar
          
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: inspect values inside producer
        run: |
          echo "FOO (set vai GITHUB_ENV):     $FOO"
          echo "foo (step output):            ${{ steps.generate-foo.outputs.foo }}

  consumer:
    runs-on: ubuntu-24.04
    needs: producer
    steps:
      - name: Inspect values inside consumer (note FOO is unset)
        run: |
          echo "Value from producer:      ${{ needs.producer.outputs.foo }}
          echo "FOO in consumer:          ${FOO:-<UNSET>}"